import Link from "next/link";

import { LegalDoc } from "@/components/marketing/legal-doc";
import { generateMarketingMetadata } from "@/lib/marketing-seo";
import { getPrivacyEmail, getSecurityEmail, legalDocumentsLastUpdatedDisplay } from "@/lib/site-constants";
import { marketingInlineLink } from "@/lib/ui-classes";
import { cn } from "@/lib/utils";

export const generateMetadata = () => generateMarketingMetadata("privacy");

const toc = [
  { id: "intro", label: "Introduction" },
  { id: "collect", label: "What we collect" },
  { id: "account", label: "Account & profile" },
  { id: "ugc", label: "User-generated content" },
  { id: "media", label: "Media & customization" },
  { id: "permissions", label: "Device permissions" },
  { id: "purchases", label: "Purchases & Sparks" },
  { id: "live", label: "Live & moderation" },
  { id: "analytics", label: "Analytics & logs" },
  { id: "use", label: "How we use data" },
  { id: "share", label: "Sharing" },
  { id: "subprocessors", label: "Subprocessors" },
  { id: "retention", label: "Retention" },
  { id: "deletion", label: "Deletion" },
  { id: "privacy-choices", label: "Privacy choices" },
  { id: "rights", label: "Your rights" },
  { id: "contact", label: "Contact" },
];

export default function PrivacyPage() {
  const privacyEmail = getPrivacyEmail();
  const securityEmail = getSecurityEmail();

  return (
    <LegalDoc title="Privacy Policy" toc={toc} breadcrumbPath="/privacy">
      <h2 id="intro">Introduction</h2>
      <p>
        This Privacy Policy describes how PulseVerse (“we”, “us”) collects, uses, shares, and retains information when
        you use our websites and applications — including Feed, Circles, My Pulse, Live, creator tools, and the Pulse
        Shop. PulseVerse is a healthcare-rooted social platform open to healthcare workers, students, caregivers,
        creators, and curious minds. Effective date: {legalDocumentsLastUpdatedDisplay}.
      </p>
      <p>
        For moderation, reporting, and safety expectations, see our{" "}
        <Link href="/trust" className={marketingInlineLink}>
          Trust &amp; safety
        </Link>{" "}
        page and{" "}
        <Link href="/community-guidelines" className={marketingInlineLink}>
          Community guidelines
        </Link>
        .
      </p>

      <h2 id="collect">What we collect</h2>
      <p>
        We collect information you provide, content you create, data generated by your use of the service, information
        from your device when you grant permissions, purchase records, trust &amp; safety records, and technical logs
        needed to operate and protect PulseVerse. The sections below describe categories in more detail.
      </p>

      <h2 id="account">Account &amp; profile data</h2>
      <p>When you register and use PulseVerse, we may collect:</p>
      <ul>
        <li>Account identifiers (email, authentication tokens, user ID)</li>
        <li>Profile fields such as display name, username, bio, avatar, audience tags, and Pulse Score</li>
        <li>Verification or professional-context information you choose to submit</li>
        <li>Settings and preferences (privacy, notifications, equipped borders, appearance choices)</li>
        <li>Follow, block, and mute relationships</li>
      </ul>

      <h2 id="ugc">User-generated content</h2>
      <p>When you use social features, we process content you create or interact with, including:</p>
      <ul>
        <li>Feed posts, videos, photos, captions, hashtags, and duets</li>
        <li>Comments, replies, reactions, saves, shares, and helpful marks</li>
        <li>Circle posts, threads, weekly prompt responses, and flair selections</li>
        <li>Live stream video, titles, chat messages, polls, reactions, and gifts</li>
        <li>My Pulse updates, vibe music selections, and profile board content</li>
        <li>Reports you submit about other content or accounts</li>
      </ul>
      <p>
        Public content may be visible to other members according to product settings and community visibility rules. Do
        not post protected health information (PHI) or individually identifiable patient details.
      </p>

      <h2 id="media">Media uploads &amp; profile customization</h2>
      <p>
        When you record, upload, or customize media, we store files and related metadata (dimensions, duration,
        thumbnails, processing status) in our storage systems. Profile customization — including avatar borders, pulse
        frames, and shop inventory — is linked to your account.
      </p>

      <h2 id="permissions">Camera, microphone, photos, notifications &amp; device permissions</h2>
      <p>
        The mobile app may request device permissions when you use related features. You can decline or revoke
        permissions in your device settings, though some features may not work without them.
      </p>
      <ul>
        <li>
          <strong>Camera &amp; microphone</strong> — recording video, going Live, and creator tools
        </li>
        <li>
          <strong>Photo library</strong> — uploading images, profile photos, and carousel posts
        </li>
        <li>
          <strong>Notifications</strong> — alerts for follows, comments, Live, trust &amp; safety updates, and product
          messages you opt into
        </li>
        <li>
          <strong>Network &amp; device data</strong> — IP address, app version, OS, locale, and crash diagnostics
        </li>
      </ul>

      <h2 id="purchases">Purchases, Sparks, gifts, borders &amp; transactions</h2>
      <p>If you make in-app purchases, we process:</p>
      <ul>
        <li>Purchase receipts and transaction IDs from Apple App Store or Google Play</li>
        <li>Sparks balance, gift sends, shop fulfillment records, and owned border inventory</li>
        <li>Support records related to billing disputes or failed fulfillment</li>
      </ul>
      <p>
        Payment card data is handled by Apple or Google — PulseVerse does not receive your full payment card number.
      </p>

      <h2 id="live">Live streaming &amp; moderation review</h2>
      <p>
        Live streams, chat, polls, and reactions may be processed in real time and reviewed for trust &amp; safety.
        Reports, automated signals, moderator notes, enforcement actions, and appeal records may be retained to protect
        the community and comply with law.
      </p>

      <h2 id="analytics">Analytics, logs, crash reporting &amp; performance</h2>
      <p>We use technical and analytics tools to keep PulseVerse reliable and secure, such as:</p>
      <ul>
        <li>Server, API, and edge logs (requests, errors, latency)</li>
        <li>Crash and error reporting (for example Sentry, when enabled)</li>
        <li>Privacy-oriented web analytics and performance metrics (for example Vercel Web Analytics / Speed Insights)</li>
        <li>Product analytics events to understand feature usage and improve the experience</li>
        <li>Attribution or campaign parameters when you arrive from a tracked marketing link</li>
      </ul>
      <p>
        We do not sell your personal information. Where analytics tools use cookies or similar technologies on the web,
        they are used for measurement and performance — not for third-party ad profiling on PulseVerse today.
      </p>

      <h2 id="use">How we use data</h2>
      <p>We use information to:</p>
      <ul>
        <li>Provide, personalize, and improve Feed, Circles, My Pulse, Live, creator tools, and the shop</li>
        <li>Recommend content and communities where product features support it</li>
        <li>Maintain safety, enforce guidelines, investigate reports, and support appeals</li>
        <li>Process purchases, deliver Sparks, gifts, and digital items</li>
        <li>Communicate with you about the service, security, and product updates</li>
        <li>Comply with law, respond to lawful requests, and defend legal claims</li>
      </ul>

      <h2 id="share">Sharing</h2>
      <p>
        We may share information with infrastructure and service vendors under contract, when required by law, to protect
        users and the public, or with your direction (for example when you share content publicly or connect third-party
        links). See{" "}
        <a href="#subprocessors" className={marketingInlineLink}>
          Subprocessors
        </a>{" "}
        below.
      </p>

      <h2 id="subprocessors">Subprocessors &amp; vendors</h2>
      <p>
        The table below describes primary providers that typically process personal data in our stack. Actual legal
        roles and data locations depend on contracts and your project region.
      </p>
      <div className={cn("mt-4 overflow-x-auto rounded-xl border border-white/10 bg-white/2")}>
        <table>
          <thead>
            <tr>
              <th scope="col">Vendor</th>
              <th scope="col">Typical role</th>
              <th scope="col">Notes</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Vercel</td>
              <td>Hosting, serverless compute, edge routing, Web Analytics / Speed Insights</td>
              <td>US / EU regions per project; see Vercel DPA.</td>
            </tr>
            <tr>
              <td>Supabase</td>
              <td>Auth, Postgres database, object storage, realtime</td>
              <td>Data region follows project configuration; primary system of record for accounts.</td>
            </tr>
            <tr>
              <td>Apple / Google</td>
              <td>In-app purchase processing</td>
              <td>Payment platforms for Sparks and digital goods on mobile.</td>
            </tr>
            <tr>
              <td>LiveKit / streaming vendors</td>
              <td>Live video transport</td>
              <td>When Live features are enabled for a session.</td>
            </tr>
            <tr>
              <td>Sentry</td>
              <td>Error and performance monitoring</td>
              <td>Optional; may receive stack traces and request metadata when enabled.</td>
            </tr>
            <tr>
              <td>Upstash</td>
              <td>Optional Redis for rate limiting</td>
              <td>Abuse protection when configured — not primary storage.</td>
            </tr>
          </tbody>
        </table>
      </div>

      <h2 id="retention">Data retention by category</h2>
      <ul>
        <li>
          <strong>Account &amp; profile</strong> — retained while your account is active and for a limited period after
          deletion where needed for safety or legal compliance
        </li>
        <li>
          <strong>Public content</strong> — may persist in backups or moderation records after deletion for integrity,
          appeals, or legal holds
        </li>
        <li>
          <strong>Purchases</strong> — retained as required for tax, fraud prevention, and platform reconciliation
        </li>
        <li>
          <strong>Trust &amp; safety</strong> — reports, enforcement, and appeal records may be kept longer to protect
          the community
        </li>
        <li>
          <strong>Logs &amp; analytics</strong> — typically rolled off on a shorter schedule unless needed for security
          investigations
        </li>
      </ul>

      <h2 id="deletion">Account deletion &amp; content deletion</h2>
      <p>
        You may delete your account from in-app Settings. When you delete your account, we remove or anonymize personal
        data associated with your profile according to this Policy, subject to retention needed for safety, legal
        obligations, dispute resolution, and fraud prevention. Some public content may be removed from active surfaces
        but remain in restricted moderation or backup systems for a limited time.
      </p>
      <p>
        To request help with deletion or export, contact{" "}
        <a href={`mailto:${privacyEmail}`} className={marketingInlineLink}>
          {privacyEmail}
        </a>
        .
      </p>

      <h2 id="privacy-choices">Privacy choices &amp; opt-outs</h2>
      <p>You can control certain data uses through product settings and your device:</p>
      <ul>
        <li>Notification preferences in app Settings</li>
        <li>Privacy settings for profile visibility and audience tags where available</li>
        <li>Device permission controls for camera, microphone, photos, and notifications</li>
        <li>Blocking, muting, and unfollowing other accounts</li>
        <li>Newsletter unsubscribe via links in product emails</li>
      </ul>
      <p>
        We do not sell personal information. If our practices change, we will update this Policy and provide additional
        choices where required by law.
      </p>

      <h2 id="rights">State &amp; global privacy rights</h2>
      <p>
        Depending on where you live, you may have rights to access, correct, delete, or export certain information, or to
        object to or restrict some processing. California and other U.S. state privacy laws, GDPR, and similar frameworks
        may apply. We may retain information where required for safety, legal compliance, or legitimate interests.
      </p>
      <p>
        Submit privacy requests to{" "}
        <a href={`mailto:${privacyEmail}`} className={marketingInlineLink}>
          {privacyEmail}
        </a>
        . We may verify your identity before fulfilling a request.
      </p>

      <h2 id="contact">Contact</h2>
      <p>
        Privacy inquiries:{" "}
        <a href={`mailto:${privacyEmail}`} className={marketingInlineLink}>
          {privacyEmail}
        </a>
      </p>
      <p>
        Security reports and responsible disclosure:{" "}
        <a href={`mailto:${securityEmail}`} className={marketingInlineLink}>
          {securityEmail}
        </a>{" "}
        — see also{" "}
        <Link href="/.well-known/security.txt" className={marketingInlineLink}>
          security.txt
        </Link>
        .
      </p>
    </LegalDoc>
  );
}
