-- ============================================================================
-- 141: High-tier creator gifts (Sparks ladder — comparable “height” to major live apps)
-- Adds marquee-priced gifts up to 99,999 Sparks. Tiers in app: lib/shop/creatorGiftTiers.ts
-- ============================================================================

insert into public.shop_items (
  slug, type, category, name, description, rarity,
  spark_price, spark_amount, real_money_display_price,
  store_product_id_ios, store_product_id_android,
  is_active, is_giftable, is_limited, sort_order, gift_contexts, metadata
)
values
  (
    'spotlight-moment',
    'gift',
    'gifts',
    'Spotlight Moment',
    'Pull the spotlight on a moment that deserved more eyes — a standout clip, post, or live beat.',
    'rare',
    1200,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    231,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  ),
  (
    'pulse-orbit',
    'gift',
    'gifts',
    'Pulse Orbit',
    'A bigger orbit of support — when their work kept your feed honest or your shift lighter.',
    'epic',
    3200,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    232,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  ),
  (
    'standing-encore',
    'gift',
    'gifts',
    'Standing Encore',
    'They earned another round — recognition that echoes past a single thank-you.',
    'epic',
    5200,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    233,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  ),
  (
    'night-residency',
    'gift',
    'gifts',
    'Night Residency',
    'For the creators who hold the late thread — nights, weekends, and the in-between.',
    'legendary',
    16000,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    234,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  ),
  (
    'healers-monument',
    'gift',
    'gifts',
    'Healer''s Monument',
    'A career-sized thank-you — the kind of gift that marks a chapter, not just a moment.',
    'exclusive',
    45000,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    235,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  ),
  (
    'pulse-nova',
    'gift',
    'gifts',
    'Pulse Nova',
    'The rarest send — when words are not enough and the community wants to go all-in.',
    'exclusive',
    99999,
    null,
    null,
    null,
    null,
    true,
    false,
    false,
    236,
    array['live', 'post', 'profile']::text[],
    '{}'::jsonb
  )
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  rarity = excluded.rarity,
  spark_price = excluded.spark_price,
  is_active = excluded.is_active,
  gift_contexts = excluded.gift_contexts,
  sort_order = excluded.sort_order,
  metadata = excluded.metadata,
  updated_at = now();
